### ISSUE TITLE
FR: Add service as div class

### ISSUE THREAD

**Issue by mikestopcontinues** [sergioramos/remark-oembed#129]
Hey, I'm trying to make my oembeds responsive, but it's a bit of a pain given the variety of configs used across services. It would be great if `div.remark-oembed-inline` included a service class (e.g. `oembed-youtube`). It would go a long way toward handling the quirks of the common services. What do you think?

**Comment by sergioramos** [comment]
thanks for the suggestion @mikestopcontinues

**Comment by mikestopcontinues** [comment]
Thank you!
